version: '3.7'
services: 
  postgres:
    image: postgres:16
    container_name: ecommerce-pg-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: password